coverage:
  precision: 2
  round: down
  range: "1...100"
  status:
    patch:
      default:
        target: auto
        threshold: 0%
    project:
      default:
        target: auto
        threshold: 1%
codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    # after_n_builds should match the number of CI jobs configured to upload reports to Codecov
    after_n_builds: 2
comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: false
