[build-system]
requires = [
    "setuptools >= 64",
    "setuptools_scm >= 7",
]
build-backend = "setuptools.build_meta"

[project]
name = "sample" 
readme = "README.md"
version = "0.1.0"
dependencies = [
    "pytest",
    "pytest-cov",
]

