name: Upload to Codecov
on:
  workflow_run:
    workflows:
      - Checks
    types:
      - completed

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:

      - name: Show event payload
        uses: actions/github-script@v7
        with:
          script: |
            txt = JSON.stringify(context.payload.workflow_run, null, 4);
            core.summary.addCodeBlock(txt, 'json');
            core.summary.write()

  upload:
    name: Upload coverage reports
    runs-on: ubuntu-latest
    steps:
      - name: Download codecov.yml file
        uses: actions/checkout@v4
        with:
          sparse-checkout: codecov.yml
          sparse-checkout-cone-mode: false
      - name: Display codecov.yml file
        run: cat codecov.yml
      - name: Download artifacts from triggering workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -lahR
          gh run download ${{ github.event.workflow_run.id }} --repo ${{ github.repository }} --pattern 'coverage-report-*'
          ls -lahR
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          name: ${{ github.event.workflow_run.display_title }}
          override_build_url: ${{ github.event.workflow_run.url }}
          override_commit: ${{ github.event.workflow_run.head_sha }}
          override_branch: ${{ github.event.workflow_run.head_branch }}
          override_pr: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.pull_requests[0].number || '' }}
